### PR TITLE
8272472: StackGuardPages test doesn't build with glibc 2.34

### PR DESCRIPTION
**Pull request by jankratochvil**
[8272472](https://bugs.openjdk.org/browse/JDK-8272472): StackGuardPages test doesn't build with glibc 2.34
```
../test/hotspot/jtreg/runtime/StackGuardPages/exeinvoke.c: In function 'set_signal_handler':
../test/hotspot/jtreg/runtime/StackGuardPages/exeinvoke.c:72:15: error: storage size of 'altstack' isn't constant
   72 |   static char altstack[SIGSTKSZ];
      |               ^~~~~~~~
```

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [JDK-8272472](https://bugs.openjdk.org/browse/JDK-8272472): StackGuardPages test doesn't build with glibc 2.34

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/crac pull/37/head:pull/37` \
`$ git checkout pull/37`

Update a local copy of the PR: \
`$ git checkout pull/37` \
`$ git pull https://git.openjdk.org/crac pull/37/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 37`

View PR using the GUI difftool: \
`$ git pr show -t 37`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/crac/pull/37.diff">https://git.openjdk.org/crac/pull/37.diff</a>

</details>

### CODE REVIEW

**Comment by AntonKozlov** [comment]
I'm not sure about this. The change was made for 18 and backported to JDK17.0.2. Instead of this, I'd prefer to continue CRaC development on JDK17u [1] or on openjdk/jdk master, to avoid backporting changes useful in general. Maintaining both will create some overhead though.

[1] https://mail.openjdk.org/pipermail/crac-dev/2022-May/000230.html

**Comment by rvansa** [comment]
@AntonKozlov So what's the plan to get CRaC builiding with new glibc? Should I create a PR to merge in the most recent jdk17u-dev?
